inherit: true

build:
    container: default
    environment:
        timezone: UTC
        hosts:
            scrutinizer.dev: 127.0.0.1
        php: '5.5.9'
        selenium:
            chrome_driver_version: 2.25
        gecko:
            gecko_driver_version: 0.11
    tests:
        override:
            -
                command: vendor/bin/phpunit; false
